export const suraList = [
  {
    id: 1,
    name: "Al-Fatihah",
    meaning: "The Opener",
    ayah_count: 7,
  },
  {
    id: 2,
    name: "Al-Baqarah",
    meaning: "The Cow",
    ayah_count: 286,
  },
  {
    id: 3,
    name: "Ali 'Imran",
    meaning: "Family of Imran",
    ayah_count: 200,
  },
  {
    id: 4,
    name: "An-Nisa",
    meaning: "The Women",
    ayah_count: 176,
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    meaning: "The Table Spread",
    ayah_count: 120,
  },
  {
    id: 6,
    name: "Al-An'am",
    meaning: "The Cattle",
    ayah_count: 165,
  },
  {
    id: 7,
    name: "Al-A'raf",
    meaning: "The Heights",
    ayah_count: 206,
  },
  {
    id: 8,
    name: "Al-Anfal",
    meaning: "The Spoils of War",
    ayah_count: 75,
  },
  {
    id: 9,
    name: "At-Tawbah",
    meaning: "The Repentance",
    ayah_count: 129,
  },
  {
    id: 10,
    name: "Yunus",
    meaning: "Jonah",
    ayah_count: 109,
  },
  {
    id: 11,
    name: "Hud",
    meaning: "Hud",
    ayah_count: 123,
  },
  {
    id: 12,
    name: "Yusuf",
    meaning: "Joseph",
    ayah_count: 111,
  },
  {
    id: 13,
    name: "Ar-Ra'd",
    meaning: "The Thunder",
    ayah_count: 43,
  },
  {
    id: 14,
    name: "Ibrahim",
    meaning: "Abraham",
    ayah_count: 52,
  },
  {
    id: 15,
    name: "Al-Hijr",
    meaning: "The Rocky Tract",
    ayah_count: 99,
  },
  {
    id: 16,
    name: "An-Nahl",
    meaning: "The Bee",
    ayah_count: 128,
  },
  {
    id: 17,
    name: "Al-Isra",
    meaning: "The Night Journey",
    ayah_count: 111,
  },
  {
    id: 18,
    name: "Al-Kahf",
    meaning: "The Cave",
    ayah_count: 110,
  },
  {
    id: 19,
    name: "Maryam",
    meaning: "Mary",
    ayah_count: 98,
  },
  {
    id: 20,
    name: "Taha",
    meaning: "Ta-Ha",
    ayah_count: 135,
  },
  {
    id: 21,
    name: "Al-Anbya",
    meaning: "The Prophets",
    ayah_count: 112,
  },
  {
    id: 22,
    name: "Al-Hajj",
    meaning: "The Pilgrimage",
    ayah_count: 78,
  },
  {
    id: 23,
    name: "Al-Mu'minun",
    meaning: "The Believers",
    ayah_count: 118,
  },
  {
    id: 24,
    name: "An-Nur",
    meaning: "The Light",
    ayah_count: 64,
  },
  {
    id: 25,
    name: "Al-Furqan",
    meaning: "The Criterion",
    ayah_count: 77,
  },
  {
    id: 26,
    name: "Ash-Shu'ara",
    meaning: "The Poets",
    ayah_count: 227,
  },
  {
    id: 27,
    name: "An-Naml",
    meaning: "The Ant",
    ayah_count: 93,
  },
  {
    id: 28,
    name: "Al-Qasas",
    meaning: "The Stories",
    ayah_count: 88,
  },
  {
    id: 29,
    name: "Al-'Ankabut",
    meaning: "The Spider",
    ayah_count: 69,
  },
  {
    id: 30,
    name: "Ar-Rum",
    meaning: "The Romans",
    ayah_count: 60,
  },
  {
    id: 31,
    name: "Luqman",
    meaning: "Luqman",
    ayah_count: 34,
  },
  {
    id: 32,
    name: "As-Sajdah",
    meaning: "The Prostration",
    ayah_count: 30,
  },
  {
    id: 33,
    name: "Al-Ahzab",
    meaning: "The Combined Forces",
    ayah_count: 73,
  },
  {
    id: 34,
    name: "Saba",
    meaning: "Sheba",
    ayah_count: 54,
  },
  {
    id: 35,
    name: "Fatir",
    meaning: "Originator",
    ayah_count: 45,
  },
  {
    id: 36,
    name: "Ya-Sin",
    meaning: "Ya Sin",
    ayah_count: 83,
  },
  {
    id: 37,
    name: "As-Saffat",
    meaning: "Those who set the Ranks",
    ayah_count: 182,
  },
  {
    id: 38,
    name: "Sad",
    meaning: 'The Letter "Saad"',
    ayah_count: 88,
  },
  {
    id: 39,
    name: "Az-Zumar",
    meaning: "The Troops",
    ayah_count: 75,
  },
  {
    id: 40,
    name: "Ghafir",
    meaning: "The Forgiver",
    ayah_count: 85,
  },
  {
    id: 41,
    name: "Fussilat",
    meaning: "Explained in Detail",
    ayah_count: 54,
  },
  {
    id: 42,
    name: "Ash-Shuraa",
    meaning: "The Consultation",
    ayah_count: 53,
  },
  {
    id: 43,
    name: "Az-Zukhruf",
    meaning: "The Ornaments of Gold",
    ayah_count: 89,
  },
  {
    id: 44,
    name: "Ad-Dukhan",
    meaning: "The Smoke",
    ayah_count: 59,
  },
  {
    id: 45,
    name: "Al-Jathiyah",
    meaning: "The Crouching",
    ayah_count: 37,
  },
  {
    id: 46,
    name: "Al-Ahqaf",
    meaning: "The Wind-Curved Sandhills",
    ayah_count: 35,
  },
  {
    id: 47,
    name: "Muhammad",
    meaning: "Muhammad",
    ayah_count: 38,
  },
  {
    id: 48,
    name: "Al-Fath",
    meaning: "The Victory",
    ayah_count: 29,
  },
  {
    id: 49,
    name: "Al-Hujurat",
    meaning: "The Rooms",
    ayah_count: 18,
  },
  {
    id: 50,
    name: "Qaf",
    meaning: 'The Letter "Qaf"',
    ayah_count: 45,
  },
  {
    id: 51,
    name: "Adh-Dhariyat",
    meaning: "The Winnowing Winds",
    ayah_count: 60,
  },
  {
    id: 52,
    name: "At-Tur",
    meaning: "The Mount",
    ayah_count: 49,
  },
  {
    id: 53,
    name: "An-Najm",
    meaning: "The Star",
    ayah_count: 62,
  },
  {
    id: 54,
    name: "Al-Qamar",
    meaning: "The Moon",
    ayah_count: 55,
  },
  {
    id: 55,
    name: "Ar-Rahman",
    meaning: "The Beneficent",
    ayah_count: 78,
  },
  {
    id: 56,
    name: "Al-Waqi'ah",
    meaning: "The Inevitable",
    ayah_count: 96,
  },
  {
    id: 57,
    name: "Al-Hadid",
    meaning: "The Iron",
    ayah_count: 29,
  },
  {
    id: 58,
    name: "Al-Mujadila",
    meaning: "The Pleading Woman",
    ayah_count: 22,
  },
  {
    id: 59,
    name: "Al-Hashr",
    meaning: "The Exile",
    ayah_count: 24,
  },
  {
    id: 60,
    name: "Al-Mumtahanah",
    meaning: "She that is to be examined",
    ayah_count: 13,
  },
  {
    id: 61,
    name: "As-Saf",
    meaning: "The Ranks",
    ayah_count: 14,
  },
  {
    id: 62,
    name: "Al-Jumu'ah",
    meaning: "The Congregation, Friday",
    ayah_count: 11,
  },
  {
    id: 63,
    name: "Al-Munafiqun",
    meaning: "The Hypocrites",
    ayah_count: 11,
  },
  {
    id: 64,
    name: "At-Taghabun",
    meaning: "The Mutual Disillusion",
    ayah_count: 18,
  },
  {
    id: 65,
    name: "At-Talaq",
    meaning: "The Divorce",
    ayah_count: 12,
  },
  {
    id: 66,
    name: "At-Tahrim",
    meaning: "The Prohibition",
    ayah_count: 12,
  },
  {
    id: 67,
    name: "Al-Mulk",
    meaning: "The Sovereignty",
    ayah_count: 30,
  },
  {
    id: 68,
    name: "Al-Qalam",
    meaning: "The Pen",
    ayah_count: 52,
  },
  {
    id: 69,
    name: "Al-Haqqah",
    meaning: "The Reality",
    ayah_count: 52,
  },
  {
    id: 70,
    name: "Al-Ma'arij",
    meaning: "The Ascending Stairways",
    ayah_count: 44,
  },
  {
    id: 71,
    name: "Nuh",
    meaning: "Noah",
    ayah_count: 28,
  },
  {
    id: 72,
    name: "Al-Jinn",
    meaning: "The Jinn",
    ayah_count: 28,
  },
  {
    id: 73,
    name: "Al-Muzzammil",
    meaning: "The Enshrouded One",
    ayah_count: 20,
  },
  {
    id: 74,
    name: "Al-Muddaththir",
    meaning: "The Cloaked One",
    ayah_count: 56,
  },
  {
    id: 75,
    name: "Al-Qiyamah",
    meaning: "The Resurrection",
    ayah_count: 40,
  },
  {
    id: 76,
    name: "Al-Insan",
    meaning: "The Man",
    ayah_count: 31,
  },
  {
    id: 77,
    name: "Al-Mursalat",
    meaning: "The Emissaries",
    ayah_count: 50,
  },
  {
    id: 78,
    name: "An-Naba",
    meaning: "The Tidings",
    ayah_count: 40,
  },
  {
    id: 79,
    name: "An-Nazi'at",
    meaning: "Those who drag forth",
    ayah_count: 46,
  },
  {
    id: 80,
    name: "'Abasa",
    meaning: "He Frowned",
    ayah_count: 42,
  },
  {
    id: 81,
    name: "At-Takwir",
    meaning: "The Overthrowing",
    ayah_count: 29,
  },
  {
    id: 82,
    name: "Al-Infitar",
    meaning: "The Cleaving",
    ayah_count: 19,
  },
  {
    id: 83,
    name: "Al-Mutaffifin",
    meaning: "The Defrauding",
    ayah_count: 36,
  },
  {
    id: 84,
    name: "Al-Inshiqaq",
    meaning: "The Sundering",
    ayah_count: 25,
  },
  {
    id: 85,
    name: "Al-Buruj",
    meaning: "The Mansions of the Stars",
    ayah_count: 22,
  },
  {
    id: 86,
    name: "At-Tariq",
    meaning: "The Nightcommer",
    ayah_count: 17,
  },
  {
    id: 87,
    name: "Al-A'la",
    meaning: "The Most High",
    ayah_count: 19,
  },
  {
    id: 88,
    name: "Al-Ghashiyah",
    meaning: "The Overwhelming",
    ayah_count: 26,
  },
  {
    id: 89,
    name: "Al-Fajr",
    meaning: "The Dawn",
    ayah_count: 30,
  },
  {
    id: 90,
    name: "Al-Balad",
    meaning: "The City",
    ayah_count: 20,
  },
  {
    id: 91,
    name: "Ash-Shams",
    meaning: "The Sun",
    ayah_count: 15,
  },
  {
    id: 92,
    name: "Al-Layl",
    meaning: "The Night",
    ayah_count: 21,
  },
  {
    id: 93,
    name: "Ad-Duhaa",
    meaning: "The Morning Hours",
    ayah_count: 11,
  },
  {
    id: 94,
    name: "Ash-Sharh",
    meaning: "The Relief",
    ayah_count: 8,
  },
  {
    id: 95,
    name: "At-Tin",
    meaning: "The Fig",
    ayah_count: 8,
  },
  {
    id: 96,
    name: "Al-'Alaq",
    meaning: "The Clot",
    ayah_count: 19,
  },
  {
    id: 97,
    name: "Al-Qadr",
    meaning: "The Power",
    ayah_count: 5,
  },
  {
    id: 98,
    name: "Al-Bayyinah",
    meaning: "The Clear Proof",
    ayah_count: 8,
  },
  {
    id: 99,
    name: "Az-Zalzalah",
    meaning: "The Earthquake",
    ayah_count: 8,
  },
  {
    id: 100,
    name: "Al-'Adiyat",
    meaning: "The Courser",
    ayah_count: 11,
  },
  {
    id: 101,
    name: "Al-Qari'ah",
    meaning: "The Calamity",
    ayah_count: 11,
  },
  {
    id: 102,
    name: "At-Takathur",
    meaning: "The Rivalry in world increase",
    ayah_count: 8,
  },
  {
    id: 103,
    name: "Al-'Asr",
    meaning: "The Declining Day",
    ayah_count: 3,
  },
  {
    id: 104,
    name: "Al-Humazah",
    meaning: "The Traducer",
    ayah_count: 9,
  },
  {
    id: 105,
    name: "Al-Fil",
    meaning: "The Elephant",
    ayah_count: 5,
  },
  {
    id: 106,
    name: "Quraysh",
    meaning: "Quraysh",
    ayah_count: 4,
  },
  {
    id: 107,
    name: "Al-Ma'un",
    meaning: "The Small kindnesses",
    ayah_count: 7,
  },
  {
    id: 108,
    name: "Al-Kawthar",
    meaning: "The Abundance",
    ayah_count: 3,
  },
  {
    id: 109,
    name: "Al-Kafirun",
    meaning: "The Disbelievers",
    ayah_count: 6,
  },
  {
    id: 110,
    name: "An-Nasr",
    meaning: "The Divine Support",
    ayah_count: 3,
  },
  {
    id: 111,
    name: "Al-Masad",
    meaning: "The Palm Fiber",
    ayah_count: 5,
  },
  {
    id: 112,
    name: "Al-Ikhlas",
    meaning: "The Sincerity",
    ayah_count: 4,
  },
  {
    id: 113,
    name: "Al-Falaq",
    meaning: "The Daybreak",
    ayah_count: 5,
  },
  {
    id: 114,
    name: "An-Nas",
    meaning: "The Mankind",
    ayah_count: 6,
  },
];
