name: Deploy in Production

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - 'server/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH Keys for heroku
        env:
          SSH_HEROKU: ${{ secrets.SSH_HEROKU }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_HEROKU" > $HOME/.ssh/id_heroku
          chmod -w $HOME/.ssh/id_heroku
          echo -e "StrictHostKeyChecking no\nHOST heroku.com\n HostName heroku.com\n IdentityFile ~/.ssh/id_heroku\n IdentitiesOnly yes" > $HOME/.ssh/config

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.16.1'

      - name: Install dependencies for client build and test
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          yarn --cwd client/

      - name: Prepare Package and deploy in heroku
        run: make heroku-deploy
